# e) Realice un análisis de sensibilidad respecto a la máxima variación posible de aluminio, pintura y trabajo, tal que no cambie la solución actual. Utilice el enfoque matricial y gráfico para determinar el rango de valores.

In [2]:
clear % eliminar todas las variables creadas previamente
clc % limpiar consola

## Función objetivo

In [3]:
function z = funcionobjetivo(x1,x2,c1)

    z = c1*x1+600*x2;

end


In [4]:
solOpt = [30,30] % x1,x2

solOpt =

   30   30



## Con el optimizador de octave se verificará lo que ocurre para valores de disponibilidad de recursos fuera o dentro del rango admisible

### Parámetros optimizador

In [5]:
%Vector de costos de función objetivo
c=[800 600 0 0 0]  
%Matriz de restricciones
A=[7 14 1 0 0; 0.3 0.3 0 -1 0;15 5 0 0 1] 
%Vector con lado derecho de restricciones
b=[630;15;600]
%Límite inferior variables
lb=[0,0,0,0,0]  
%Límite superior variables
ub=[]
%Tipo de restricciones
ctype='SSS'
%Tipo de variables
vartype='CCCCC'
%Opción para el tipo de output del optimizador
param.msglev=2;

c =

   800   600     0     0     0

A =

    7.00000   14.00000    1.00000    0.00000    0.00000
    0.30000    0.30000    0.00000   -1.00000    0.00000
   15.00000    5.00000    0.00000    0.00000    1.00000

b =

   630
    15
   600

lb =

   0   0   0   0   0

ub = [](0x0)
ctype = SSS
vartype = CCCCC


### A continuación se verificará que para disponibilidad de recursos que están dentro del rango encontrado, la base óptima no cambia.

i) $b_1= 1679$

In [24]:
%Vector con lado derecho de restricciones
b=[1679;15;600]
#Ejecución del optimizador
[xOpt,fOpt]= glpk(c=c,A=A,B=b,lb=lb,ub=ub,ctype=ctype,vartype=vartype,s=-1,param=param)

b =

   1679
     15
    600

      0: obj =  -0.000000000e+00 inf =   4.518e+01 (1)
      1: obj =   3.000000000e+04 inf =   0.000e+00 (0)
*     3: obj =   7.197142857e+04 inf =   0.000e+00 (0)
xOpt =

     0.02857
   119.91429
     0.00000
    20.98286
     0.00000

fOpt =  71971.42857


ii) $b_1= 456$

In [26]:
%Vector con lado derecho de restricciones
b=[456;15;600]
#Ejecución del optimizador
[xOpt,fOpt]= glpk(c=c,A=A,B=b,lb=lb,ub=ub,ctype=ctype,vartype=vartype,s=-1,param=param)

b =

   456
    15
   600

      0: obj =  -0.000000000e+00 inf =   4.518e+01 (1)
      2: obj =   3.697142857e+04 inf =   0.000e+00 (0)
*     3: obj =   3.702857143e+04 inf =   0.000e+00 (0)
xOpt =

   34.97143
   15.08571
    0.00000
    0.01714
    0.00000

fOpt =  37028.57143


* Ahora se verificará que disponibilidad de recursos fuera del rango encontrado, la base óptima cambia o no es factible

iii) $b_1 = 434$

In [29]:
b=[434;15;600]
#Ejecución del optimizador
[xOpt,fOpt]= glpk(c=c,A=A,B=b,lb=lb,ub=ub,ctype=ctype,vartype=vartype,s=-1,param=param)

b =

   434
    15
   600

      0: obj =  -0.000000000e+00 inf =   4.518e+01 (1)
      2: obj =   3.640000000e+04 inf =   1.084e+00 (1)
glp_simplex: unable to recover undefined or non-optimal solution
xOpt =

    NA
    NA
    NA
    NA
    NA

fOpt =   NA


Si la disponibilidad de recursos de aluminio bruto es menor a 435 (434 < 435), no hay solución factible

iv) $b_1 = 1681$

In [30]:
b=[1681;15;600]
#Ejecución del optimizador
[xOpt,fOpt]= glpk(c=c,A=A,B=b,lb=lb,ub=ub,ctype=ctype,vartype=vartype,s=-1,param=param)

b =

   1681
     15
    600

      0: obj =  -0.000000000e+00 inf =   4.518e+01 (1)
      1: obj =   3.000000000e+04 inf =   0.000e+00 (0)
*     2: obj =   7.200000000e+04 inf =   0.000e+00 (0)
xOpt =

     0
   120
     1
    21
     0

fOpt =  72000


Si la disponibilidad de recursos de aluminio bruto es mayor a 1680 (1681 < 1680), $x_1$ sale de la base y $x_3$ entra a la base <br/> Es decir, respecto al caso original, no se producen planchas de aluminio tipo 1 y la restricción asociada a la disponibilidad de aluminio bruto deja de ser activa

## * Repita el ejercicio de forma personal para los ingresos netos asociados a la plancha de aluminio tipo 2